name: Laravel

on:
  push:
    branches: ["master"]

jobs:
  Gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

  ManualApproval:
    needs: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Vaskonti
          minimum-approvals: 1
          issue-title: "Deploying to server"
          issue-body: "Please approve or deny the deployment to server"
          exclude-workflow-initiator-as-approver: false

  DeployToProd:
    needs: [ManualApproval]
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate for AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODE_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Prod
        uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
      - name: Deployment notes
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=eu-central-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.
